# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-08-24 16:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('snap', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='catch',
            name='coordinates',
            field=models.CharField(max_length=40, null=True),
        ),
    ]
