# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-08-25 00:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('snap', '0002_catch_coordinates'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='fbook_auth_id',
            field=models.CharField(default=0, max_length=512),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='user',
            name='name',
            field=models.CharField(blank=True, max_length=40),
        ),
    ]
