# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-24 23:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('snap', '0002_catch_coordinates'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='name',
            field=models.CharField(blank=True, max_length=40),
        ),
    ]
