# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-08-25 13:34
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('snap', '0003_auto_20170825_0033'),
        ('snap', '0003_auto_20170824_2313'),
    ]

    operations = [
    ]
