# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-08-25 18:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('snap', '0004_merge_20170825_1334'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='fbook_auth_id',
            field=models.CharField(max_length=512, unique=True),
        ),
    ]
